#include <string.h>
#include <xenctrl.h>
#include <xendevicemodel.h>
#include <xenevtchn.h>
#include <xenforeignmemory.h>
#include <xenstore.h>
#include <xen/hvm/ioreq.h>
#include <xen/io/xenbus.h>
#include <linux/virtio_mmio.h>
#include <linux/virtio_ids.h>
#include "src/mb.h"
